name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install buildozer

    - name: Prepare Buildozer spec file
      run: |
        echo 'requirements = flet' >> buildozer.spec
        echo 'source.include_exts = py,kv' >> buildozer.spec
        echo 'android.arch = arm64-v8a' >> buildozer.spec
        echo 'title = MyFletApp' >> buildozer.spec
        echo 'package.name = myfletapp' >> buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyFletApp-apk
        path: bin/*.apk
